language: node_js
node_js:
  - '6.10.2'
addons:
  apt:
    packages:
    - graphicsmagick
email: false
after_success:
  - './node_modules/.bin/nyc report --reporter=text-lcov | ./node_modules/.bin/coveralls'